"""
Scrapes Wikipedia summaries and thumbnail images for all ancestor nodes in the game tree.
Reads:  <dataset>/taxon_list.json   (generated by: python3 datagen/build_taxon_list.py)
Writes: <dataset>/taxon_info.json   — atomically, so an interrupted run cannot
        destroy existing entries; rerunning resumes from the last checkpoint.

Usage:
    python3 scrape_taxon_info.py              # scrape all, skip already-done
    python3 scrape_taxon_info.py --retry-missing   # also retry entries with no extract

The Wikipedia REST summary API returns:
    extract       — first paragraph, plain text
    thumbnail.source — image URL (resized)
    content_urls.desktop.page — full Wikipedia URL
"""

import json
import time
import argparse
import urllib.request
import urllib.parse
import urllib.error
import sys
import os

SUMMARY_API = "https://en.wikipedia.org/api/rest_v1/page/summary/{title}"
WIKIDATA_API = "https://www.wikidata.org/wiki/Special:EntityData/{qid}.json"
HEADERS = {"User-Agent": "TaxoQuiz/1.0 (https://github.com/markharley12/TaxoQuiz)"}
DELAY = 0.5  # seconds between requests — be polite

from taxoquiz.jsonio import read_json, write_json_atomic
from taxoquiz.paths import current_dataset, taxon_info_path, taxon_list_path

OUT_PATH = taxon_info_path()
LIST_PATH = taxon_list_path()


def fetch_json(url: str) -> dict | None:
    req = urllib.request.Request(url, headers=HEADERS)
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return None
        print(f"  HTTP {e.code}: {url}", file=sys.stderr)
        return None
    except Exception as e:
        print(f"  Error fetching {url}: {e}", file=sys.stderr)
        return None


def fetch_by_title(title: str) -> dict | None:
    url = SUMMARY_API.format(title=urllib.parse.quote(title, safe=""))
    return fetch_json(url)


def fetch_by_qid(qid: str) -> dict | None:
    """Get the English Wikipedia title from Wikidata, then fetch the summary."""
    data = fetch_json(WIKIDATA_API.format(qid=qid))
    if not data:
        return None
    entity = data.get("entities", {}).get(qid, {})
    sitelinks = entity.get("sitelinks", {})
    enwiki = sitelinks.get("enwiki", {})
    title = enwiki.get("title")
    if not title:
        return None
    time.sleep(DELAY)
    return fetch_by_title(title)


def extract_info(summary: dict) -> dict:
    return {
        "description": summary.get("extract", ""),
        "image_url": (summary.get("thumbnail") or {}).get("source", ""),
        "wikipedia_url": summary.get("content_urls", {}).get("desktop", {}).get("page", ""),
        "wikipedia_title": summary.get("title", ""),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--retry-missing", action="store_true",
                        help="Re-fetch entries that previously returned no extract")
    args = parser.parse_args()

    print(f"dataset: {current_dataset()}")
    if not LIST_PATH.exists():
        sys.exit(f"{LIST_PATH} does not exist — run build_taxon_list.py first.")
    taxon_list = read_json(LIST_PATH)

    # Load existing results. Writes below are atomic, so an interrupted run can
    # never destroy what is already here — it resumes from the last checkpoint.
    if OUT_PATH.exists():
        results: dict[str, dict] = read_json(OUT_PATH)
        print(f"Loaded {len(results)} existing entries from {OUT_PATH}")
    else:
        results = {}

    to_process = []
    for taxon in taxon_list:
        name = taxon["name"]
        if name in results:
            if not args.retry_missing:
                continue
            if results[name].get("description"):
                continue  # already has content, skip
        to_process.append(taxon)

    print(f"Processing {len(to_process)} taxa (of {len(taxon_list)} total)...")

    for i, taxon in enumerate(to_process):
        name = taxon["name"]
        qid = taxon.get("qid")
        rank = taxon.get("rank", "")
        pct = f"{i+1}/{len(to_process)}"

        # Try Wikipedia directly by scientific name first
        summary = fetch_by_title(name)
        time.sleep(DELAY)

        if not summary or not summary.get("extract"):
            # Fall back to Wikidata lookup via Q-ID
            if qid:
                print(f"[{pct}] {name} ({rank}) — not found by name, trying Q-ID {qid}")
                summary = fetch_by_qid(qid)
                time.sleep(DELAY)
            else:
                print(f"[{pct}] {name} ({rank}) — not found, no Q-ID fallback")

        if summary and summary.get("extract"):
            info = extract_info(summary)
            results[name] = {"rank": rank, "qid": qid, **info}
            print(f"[{pct}] {name} ({rank}) — OK ({len(info['description'])} chars)")
        else:
            results[name] = {"rank": rank, "qid": qid, "description": "", "image_url": "", "wikipedia_url": "", "wikipedia_title": ""}
            print(f"[{pct}] {name} ({rank}) — no data found")

        # Save incrementally every 50 entries
        if (i + 1) % 50 == 0:
            write_json_atomic(OUT_PATH, results)
            print(f"  → saved checkpoint ({len(results)} entries)")

    write_json_atomic(OUT_PATH, results)

    found = sum(1 for v in results.values() if v.get("description"))
    print(f"\nDone. {found}/{len(results)} taxa have descriptions.")
    print(f"Output: {OUT_PATH}")


if __name__ == "__main__":
    main()
