import json

from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel

from ..game.pick_animal import pick_random_animal
from ..game.list_animals import list_animals, DEFAULT_LIMIT
from ..game.game_state import get_game_state
from ..game.tree import load_tree, get_species
from ..paths import data_dir, tree_path, using_example_tree

app = FastAPI(title="TaxoQuiz", description="TaxoQuiz game API")

# Optional: only the taxon info popup needs this, and it is generated by the
# datagen/ pipeline rather than shipped. The API starts fine without it.
try:
    with open(data_dir() / "taxon_info.json") as _f:
        _taxon_info: dict = json.load(_f)
except FileNotFoundError:
    _taxon_info = {}


def _max_depth(node: dict, depth: int = 0) -> int:
    if not node.get("children"):
        return depth
    return max(_max_depth(c, depth + 1) for c in node["children"])


@app.get("/dataset", tags=["dataset"])
def dataset():
    """Which dataset is loaded, and how deep it goes.

    Exists because "am I playing the bundled example or my own scrape?" was
    otherwise unanswerable without reading the environment. `max_depth` also
    drives the frontend's colour gradient, which would otherwise hardcode a
    number only correct for the example.
    """
    tree = load_tree()
    return {
        "source": "example" if using_example_tree() else "custom",
        "path": str(tree_path()),
        "root": tree["name"],
        "species": len(get_species(tree)),
        "max_depth": _max_depth(tree),
        "taxon_info": len(_taxon_info),
    }


@app.get("/animal/random", response_model=str, tags=["animals"])
def random_animal(daily: bool = False):
    """Pick a random animal. Pass `daily=true` for today's seeded daily animal."""
    return pick_random_animal(daily=daily)


@app.get("/animals", response_model=list[str], tags=["animals"])
def autocomplete(
    q: str = Query(..., description="Substring to search for"),
    limit: int = Query(DEFAULT_LIMIT, ge=1, le=200),
    exclude: list[str] = Query(default=[], description="Animal names to exclude from results"),
):
    """Return up to `limit` animal common names containing `q`."""
    return list_animals(q, limit, set(exclude) or None)


class GameStateRequest(BaseModel):
    secret: str
    guesses: list[str]


@app.post("/game/state", tags=["game"])
def game_state(body: GameStateRequest):
    """
    Return the annotated tree for the current game state.

    Each node carries `label`, `node_type`, `depth`, `on_secret_path`, and `children`.
    Returns 400 if any name (secret or guess) is not in the dataset.
    """
    try:
        return get_game_state(body.secret, body.guesses)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@app.get("/taxon/{name}", tags=["taxon"])
def taxon_info(name: str):
    """Return Wikipedia summary and image for a taxon node."""
    info = _taxon_info.get(name)
    if info is None:
        raise HTTPException(status_code=404, detail=f"No info for '{name}'")
    return info
