from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel

from ..game.pick_animal import pick_random_animal
from ..game.list_animals import list_animals, DEFAULT_LIMIT
from ..game.game_state import get_game_state
from ..game.tree import load_tree, get_species
from ..jsonio import read_json
from ..paths import (
    available_datasets, current_dataset, taxon_info_path, tree_path, using_example,
)

app = FastAPI(title="TaxoQuiz", description="TaxoQuiz game API")

# Optional: only the taxon-info popup needs this, and it is generated by the
# datagen/ pipeline rather than shipped. The API starts fine without it, and the
# popup reports "no information available" per taxon.
try:
    _taxon_info: dict = read_json(taxon_info_path())
except FileNotFoundError:
    _taxon_info = {}


def _species_depths(node: dict, depth: int = 0, out: list | None = None) -> list:
    out = [] if out is None else out
    if not node.get("children"):
        out.append(depth)
    else:
        for child in node["children"]:
            _species_depths(child, depth + 1, out)
    return out


# Percentile of species depth used as the "fully green" end of the colour scale.
#
# Anchoring on the deepest lineage in the tree sounds right and plays badly: in
# the Wikidata scrape that is Human at 59 of a 64-deep tree, while the median
# species sits at 26. Scaled against 64, a median secret tops out yellow-orange
# even when you guess its own genus — so more than half of all games could never
# look warm however well they were played. A high percentile keeps the scale
# absolute (a given depth is always the same colour, and nothing about the
# secret leaks) while letting a typical game actually reach green. Depths past
# the anchor clamp.
COLOR_ANCHOR_PERCENTILE = 75


@app.get("/dataset", tags=["dataset"])
def dataset():
    """Which dataset is loaded, how big it is, and how to colour it.

    Exists because "am I playing the example or my own scrape?" was otherwise
    unanswerable without reading the environment — and because the frontend
    needs the depth scale, which differs by a factor of three between datasets.
    """
    tree = load_tree()
    depths = sorted(_species_depths(tree))
    anchor = depths[min(len(depths) - 1, len(depths) * COLOR_ANCHOR_PERCENTILE // 100)]
    return {
        "dataset": current_dataset(),
        "is_example": using_example(),
        "available": available_datasets(),
        "path": str(tree_path()),
        "root": tree["name"],
        "species": len(depths),
        "max_depth": depths[-1],
        "color_anchor_depth": anchor,
        "taxon_info": len(_taxon_info),
    }


@app.get("/animal/random", response_model=str, tags=["animals"])
def random_animal(daily: bool = False):
    """Pick a random animal. Pass `daily=true` for today's seeded daily animal."""
    return pick_random_animal(daily=daily)


@app.get("/animals", response_model=list[str], tags=["animals"])
def autocomplete(
    q: str = Query(..., description="Substring to search for"),
    limit: int = Query(DEFAULT_LIMIT, ge=1, le=200),
    exclude: list[str] = Query(default=[], description="Animal names to exclude from results"),
):
    """Return up to `limit` animal common names containing `q`."""
    return list_animals(q, limit, set(exclude) or None)


class GameStateRequest(BaseModel):
    secret: str
    guesses: list[str]


@app.post("/game/state", tags=["game"])
def game_state(body: GameStateRequest):
    """
    Return the annotated tree for the current game state.

    Each node carries `label`, `node_type`, `depth`, `on_secret_path`, and `children`.
    Returns 400 if any name (secret or guess) is not in the dataset.
    """
    try:
        return get_game_state(body.secret, body.guesses)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@app.get("/taxon/{name}", tags=["taxon"])
def taxon_info(name: str):
    """Return Wikipedia summary and image for a taxon node."""
    info = _taxon_info.get(name)
    if info is None:
        raise HTTPException(status_code=404, detail=f"No info for '{name}'")
    return info
